### ISSUE TITLE
Bug in SURF sum_rect()

### ISSUE THREAD

**Issue by Mimino666** [luispedro/mahotas#58]
Shouldn't the lines 42 and 43 in file https://github.com/luispedro/mahotas/blob/master/mahotas/features/_surf.cpp be:
```cpp
y1 = std::min<int>(y1, integral.dim(0)-1);
x1 = std::min<int>(x1, integral.dim(1)-1);
```
?

**Comment by luispedro** [comment]
I think you're right that those lines are wrong, though my feeling is that it should be

    y1 = std::min<int>(y1 - 1, integral.dim(0)-1);
    x1 = std::min<int>(x1 - 1, integral.dim(1)-1);

It needs to be y1-1 because the outward facing interface is that we are computing `array[y0:y1, x0:x1]`, so it should be `integral[y1,x1] - integral[y0,x0]`. The bounds check is useless, though.

I'll check this more carefully and commit the fix.

Thanks Luis
